### ISSUE TITLE
Stick overlay improvements

### ISSUE THREAD

**Issue by stylesuxx** [betaflight/blackbox-tools#13]
Hey,
@j4y4r and I made some changes to the blackbox-tools over in the cleanflight repo => https://github.com/cleanflight/blackbox-tools/pull/25 But now I am not sure if we should not have made them against this repo, the cleanflight repo seems rather dead - what do you think, should I make the PR against this repo?

**Comment by mikeller** [comment]
@stylesuxx: Yes please. :-)

**Comment by mikeller** [comment]
@stylesuxx: We are still interested in these changes in Betaflight.

**Comment by j4y4r** [comment]
@mikeller changes are now in https://github.com/betaflight/blackbox-tools/pull/27
