### ISSUE TITLE
Increase max logs in file

### ISSUE THREAD

**Issue by cpihl** [betaflight/blackbox-tools#16]
In parser.h, FLIGHT_LOG_MAX_LOGS_IN_FILE is set to 31,
and I have seen log files with 97 logs. For example when using Betaflight F4 with Betaflight 3.5.5.
Tested to increase to 100 and it worked. (Why limit?)

**Comment by mikeller** [comment]
It's probably arbitrary and comes from a time when flash chips on boards were smaller. It should be save to increase it. Can you please open a pull request for this change?
