### ISSUE TITLE
Cannot find executables for windows

### ISSUE THREAD

**Issue by Mahdi-Hosseinali** [betaflight/blackbox-tools#31]
I want to run the decoder through python, so logically I should use the executables (unfortunately on a windows machine) but I cannot find them in the latest release.

**Comment by mikeller** [comment]
@Mahdi-Hosseinali: We normally do not do releases for the Blackbox tools, as the people using them are normally set up to build the executables themselves.
I'll build some executables, and post them here.

**Comment by mikeller** [comment]
@Mahdi-Hosseinali: Sorry for slacking on this. It looks like the current version is not buildable under Windows, and will need some fixing first. Not sure if anybody who is using this is working on it.
