### ISSUE TITLE
Problems compiling for Windows

### ISSUE THREAD

**Issue by xRealNeon** [betaflight/blackbox-tools#35]
Hi
I try to compile the blackbox tools on windows but i get errors all the time.

> File (Include) cannot be opened: "unistd.h": No such file or directory

**Comment by xRealNeon** [comment]
I followed the instructions in the readme

**Comment by xRealNeon** [comment]
What informations are missing? @mikeller

**Comment by mikeller** [comment]
@xRealNeon: The information that you were asked to provide when you opened this issue.

**Comment by xRealNeon** [comment]
Describe your problem:I try to compile the blackbox tools on windows but i get errors all the time.
Include ways to reproduce the problem: 

> The tools can be built with Visual Studio Express 2013, just open up the solution in the visual-studio/ folder. You'll need to include the .DLL files from lib/win32 in the same directory as your built executable.

what hardware / software you are using: WIndows 10, Microsoft Visual Studio Community 2019
Version 16.5.3

**Comment by mikeller** [comment]
@xRealNeon: Ok, looks like the building the blackbox tools in Windows does not work with the versions that you are using - how about you try using the versions described as working in the Readme?

**Comment by xRealNeon** [comment]
![grafik](https://user-images.githubusercontent.com/20997346/79072232-34e28380-7ce0-11ea-8f78-c030c14b7a15.png)
I got these errors

**Comment by xRealNeon** [comment]
with the version from the readme

**Comment by xRealNeon** [comment]
Can you just precompile it and make a release in Github? @mikeller

**Comment by mikeller** [comment]
@xRealNeon: There has not been much change, you can probably use one of the existing releases.

**Comment by xRealNeon** [comment]
@mikeller in the github releases are no binaries.
