### ISSUE TITLE
Units of angle in converted csv file

### ISSUE THREAD

**Issue by artur-iluk** [betaflight/blackbox-tools#39]
While converting *.BFL file to *.csv in the headers of csv there are units of barometer (cm), rotational velocity in ex. (deg/s) and acceleration (m/s/s) if the units were selected by command line switches. But there in no command line switch to select units of attitude provided when --simulate-imu is activated.

The orientation angles are not raw values,, are in (deg). To have consistent file, the units of angle should be added to roll, pitch and yaw in headers

It is now:
accSmooth[0] (m/s/s)   accSmooth[1] (m/s/s)   accSmooth[2] (m/s/s)   roll   pitch   heading

It should be:
accSmooth[0] (m/s/s)   accSmooth[1] (m/s/s)   accSmooth[2] (m/s/s)   roll(deg)   pitch(deg)   heading(deg)

To see it, it is necessary to use --simulate-imu option

**Comment by mikeller** [comment]
Not sure if this should be a bug or a missing feature, but seems to be reasonable. Thanks for bringing this up, feel free to open a pull request to implement this.

**Comment by artur-iluk** [comment]
For me it can be treated as a bug - missing significant information.

I know that change is simple, but I'm just a user of software and don't know how to modify the soft. I'm not familiar with github as well, so I'm not a person to make a pull request (requires some code?). It was just proposal of me.

I hope someone more proficient will have some time to modify the code make a pull request. It is probably small change.
