### ISSUE TITLE
Serial protocol

### ISSUE THREAD

**Issue by grausof** [betaflight/blackbox-tools#42]
is it possible to know the protocol used for logging the blackbox via serial? I need to access the gyro data via Arduino. Currently I can communicate via serial but I do not know the protocol to access this data. 
Is there a start and end iteration bit?

Thanks

**Comment by xsnoopy** [comment]
Hey grausof,

this questions has more to do with the blackbox part in the firmware. You asking at the blackbox-tools view is for all the post work after the log has been created in the firmware. 

I would look here https://github.com/betaflight/betaflight/blob/master/docs/development/Blackbox%20Internals.md 
or in the source code https://github.com/betaflight/betaflight/tree/master/src/main/blackbox

**Comment by grausof** [comment]
Thanks!
